export const text = {
  en: {
    title: "Find Vesak Dansal Near You",
    desc: "Check food availability, queue status and location updates in real time.",
    search: "Search area, food, location...",
    live: "Live Dansals",
    found: "found",
    add: "+ Add Dansal",
    addTitle: "🏮 Add New Dansal",
    addDesc: "Add correct details so people can quickly find food, queue and location.",
    name: "Dansal Name",
    food: "Food Type",
    area: "Main Area",
    exact: "Exact Location",
    map: "Google Maps Link",
    date: "Date",
    time: "Time",
    submit: "Submit Dansal 🏮",
    back: "← Back",
  },

  si: {
    title: "ඔබ අසල වෙසක් දන්සල් සොයන්න",
    desc: "ආහාර තිබේද, පෝලිමේ තත්ත්වය සහ ස්ථානය සජීවීව බලන්න.",
    search: "ප්‍රදේශය, ආහාරය හෝ ස්ථානය සොයන්න...",
    live: "සජීවී දන්සල්",
    found: "ක් හමු විය",
    add: "+ දන්සලක් එක් කරන්න",
    addTitle: "🏮 නව දන්සලක් එක් කරන්න",
    addDesc: "අන් අයට ආහාර, පෝලිම සහ ස්ථානය පහසුවෙන් සොයාගැනීමට නිවැරදි විස්තර එක් කරන්න.",
    name: "දන්සලේ නම",
    food: "ආහාර වර්ගය",
    area: "ප්‍රධාන ප්‍රදේශය",
    exact: "නිශ්චිත ස්ථානය",
    map: "Google Maps Link",
    date: "දිනය",
    time: "වේලාව",
    submit: "දන්සල එක් කරන්න 🏮",
    back: "← ආපසු",
  },
};